// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gpu-storages": {
            "get": {
                "description": "List RBD-backed GPU storage resources in the shared runtime instance namespace, including prepare-job and accessor status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "List GPU storages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUStorageListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Persist a GPUStorage resource. By default it targets the rook-ceph-block RBD StorageClass, and the controller reconciles the backing PersistentVolumeClaim, prepare job, and optional accessor asynchronously.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Create a GPU storage",
                "parameters": [
                    {
                        "description": "Create GPU storage request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateGPUStorageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.GPUStorageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/gpu-storages/{name}": {
            "get": {
                "description": "Get the desired and observed state of one GPUStorage resource.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Get a GPU storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU storage name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUStorageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the mutable storage fields on a GPUStorage resource. This chapter allows storage expansion and accessor toggling, while prepare workflows stay immutable and recoverable through a dedicated action.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Update a GPU storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU storage name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update GPU storage request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateGPUStorageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUStorageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a GPUStorage resource after verifying that no active GPU unit still mounts it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Delete a GPU storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU storage name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/gpu-storages/{name}/recover": {
            "post": {
                "description": "Request a new prepare attempt for one GPUStorage resource after a failed data job.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Recover a GPU storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU storage name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUStorageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/gpu-units": {
            "get": {
                "description": "List active GPU unit resources in the fixed runtime instance namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runtime"
                ],
                "summary": "List GPU units",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUUnitListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Persist an active DRA-backed GPUUnit from a configured packageID, runtime image, template, access settings, and storage mounts. Replays with the same operationID and payload are idempotent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runtime"
                ],
                "summary": "Create a GPU unit",
                "parameters": [
                    {
                        "description": "Create GPU unit request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.CreateGPUUnitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUUnitResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.GPUUnitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/gpu-units/{name}": {
            "get": {
                "description": "Get the current desired and observed state of one active GPU unit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runtime"
                ],
                "summary": "Get a GPU unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU unit name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUUnitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the mutable runtime contract of an active GPU unit, including image, template, access settings, and storage mounts.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runtime"
                ],
                "summary": "Update a GPU unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU unit name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update GPU unit request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateGPUUnitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUUnitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an active GPU unit resource and let Kubernetes garbage collection clean up the owned runtime objects.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runtime"
                ],
                "summary": "Delete a GPU unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU unit name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Return process and Kubernetes connectivity health for the runtime server.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operator/inventory": {
            "get": {
                "description": "Return the Kubernetes-derived allocation view used by the runtime API: node GPU allocatable, requested GPU from GPUUnit objects, and ResourceQuota status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operator"
                ],
                "summary": "Get runtime inventory",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.InventoryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/serverless/invocations": {
            "post": {
                "description": "Persist one serverless invocation into the configured NATS JetStream ingress stream. Async mode returns the durable enqueue acknowledgement, while sync mode waits on the invocation-specific reply subject for the worker-side result path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serverless"
                ],
                "summary": "Enqueue a serverless invocation",
                "parameters": [
                    {
                        "description": "Create serverless invocation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.CreateServerlessInvocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ServerlessInvocationResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.ServerlessInvocationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.APIError"
                }
            }
        },
        "api.GPUStorageListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GPUStorageRuntime"
                    }
                }
            }
        },
        "api.GPUStorageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GPUStorageRuntime"
                }
            }
        },
        "api.GPUUnitListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GPUUnitRuntime"
                    }
                }
            }
        },
        "api.GPUUnitResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GPUUnitRuntime"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.HealthStatus"
                }
            }
        },
        "api.InventoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.RuntimeInventoryStatus"
                }
            }
        },
        "api.ServerlessInvocationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.ServerlessInvocationAck"
                }
            }
        },
        "contract.CreateGPUUnitRequest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitAccess"
                },
                "cpu": {
                    "type": "string"
                },
                "gpu": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operationID": {
                    "type": "string"
                },
                "packageID": {
                    "type": "string"
                },
                "serverless": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitServerlessSpec"
                },
                "specName": {
                    "type": "string"
                },
                "ssh": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitSSHSpec"
                },
                "storageMounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.GPUUnitStorageMount"
                    }
                },
                "template": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitTemplate"
                }
            }
        },
        "contract.CreateServerlessInvocationRequest": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "contentType": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "invocationID": {
                    "type": "string"
                },
                "mode": {
                    "$ref": "#/definitions/serverless.InvocationMode"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "serverlessRequestID": {
                    "type": "string"
                },
                "timeoutSeconds": {
                    "type": "integer"
                }
            }
        },
        "contract.UpdateGPUUnitRequest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitAccess"
                },
                "image": {
                    "type": "string"
                },
                "serverless": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitServerlessSpec"
                },
                "ssh": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitSSHSpec"
                },
                "storageMounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.GPUUnitStorageMount"
                    }
                },
                "template": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitTemplate"
                }
            }
        },
        "domain.GPUProductHealth": {
            "type": "object",
            "properties": {
                "allocatable": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "nodeCount": {
                    "type": "integer"
                },
                "product": {
                    "type": "string"
                }
            }
        },
        "domain.GPUStorageRuntime": {
            "type": "object",
            "properties": {
                "accessor": {
                    "$ref": "#/definitions/v1alpha1.GPUStorageAccessorSpec"
                },
                "accessorStatus": {
                    "$ref": "#/definitions/v1alpha1.GPUStorageAccessorStatus"
                },
                "capacity": {
                    "type": "string"
                },
                "claimName": {
                    "type": "string"
                },
                "lastSyncTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "mountedBy": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "observedGeneration": {
                    "type": "integer"
                },
                "phase": {
                    "type": "string"
                },
                "prepare": {
                    "$ref": "#/definitions/v1alpha1.GPUStoragePrepareSpec"
                },
                "prepareStatus": {
                    "$ref": "#/definitions/v1alpha1.GPUStoragePrepareStatus"
                },
                "reason": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "storageClassName": {
                    "type": "string"
                }
            }
        },
        "domain.GPUUnitRuntime": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitAccess"
                },
                "accessURL": {
                    "type": "string"
                },
                "allocation": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitAllocationSpec"
                },
                "cpu": {
                    "type": "string"
                },
                "draStatus": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitDRAStatus"
                },
                "gpu": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "lastSyncTime": {
                    "type": "string"
                },
                "lifecycle": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "observedGeneration": {
                    "type": "integer"
                },
                "packageID": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "readyReplicas": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "serverless": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitServerlessSpec"
                },
                "serverlessStatus": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitServerlessStatus"
                },
                "serviceName": {
                    "type": "string"
                },
                "specName": {
                    "type": "string"
                },
                "ssh": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitSSHSpec"
                },
                "sshStatus": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitSSHStatus"
                },
                "storageMounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.GPUUnitStorageMount"
                    }
                },
                "template": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitTemplate"
                }
            }
        },
        "domain.HealthStatus": {
            "type": "object",
            "properties": {
                "activeUnitCount": {
                    "type": "integer"
                },
                "averageGpuUtilizationPercent": {
                    "type": "number"
                },
                "freeGpuMemoryMiB": {
                    "type": "number"
                },
                "gpuDeviceCount": {
                    "type": "integer"
                },
                "gpuProducts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GPUProductHealth"
                    }
                },
                "kubeError": {
                    "type": "string"
                },
                "kubernetesConnected": {
                    "type": "boolean"
                },
                "nodeCount": {
                    "type": "integer"
                },
                "nvidiaMetricsConnected": {
                    "type": "boolean"
                },
                "nvidiaMetricsError": {
                    "type": "string"
                },
                "readyNodeCount": {
                    "type": "integer"
                },
                "startedAt": {
                    "type": "string"
                },
                "totalGPUAllocatable": {
                    "type": "integer"
                },
                "totalGPUCapacity": {
                    "type": "integer"
                },
                "totalGpuMemoryMiB": {
                    "type": "number"
                },
                "uptimeSeconds": {
                    "type": "integer"
                },
                "usedGpuMemoryMiB": {
                    "type": "number"
                }
            }
        },
        "domain.RuntimeDRADeviceStatus": {
            "type": "object",
            "properties": {
                "claimName": {
                    "type": "string"
                },
                "consumedCapacity": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "device": {
                    "type": "string"
                },
                "driver": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "pool": {
                    "type": "string"
                },
                "request": {
                    "type": "string"
                },
                "shareID": {
                    "type": "string"
                }
            }
        },
        "domain.RuntimeInventoryStatus": {
            "type": "object",
            "properties": {
                "draAllocatedClaims": {
                    "type": "integer"
                },
                "draAllocatedDevices": {
                    "type": "integer"
                },
                "draClaimCount": {
                    "type": "integer"
                },
                "draDevices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RuntimeDRADeviceStatus"
                    }
                },
                "draResourceSlices": {
                    "type": "integer"
                },
                "gpuProducts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GPUProductHealth"
                    }
                },
                "kubernetesConnected": {
                    "type": "boolean"
                },
                "nodeCount": {
                    "type": "integer"
                },
                "readyNodeCount": {
                    "type": "integer"
                },
                "resourceQuotas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RuntimeQuotaStatus"
                    }
                },
                "totalGpuAllocatable": {
                    "type": "integer"
                },
                "totalGpuCapacity": {
                    "type": "integer"
                }
            }
        },
        "domain.RuntimeQuotaStatus": {
            "type": "object",
            "properties": {
                "hard": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "used": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.ServerlessInvocationAck": {
            "type": "object",
            "properties": {
                "acceptedAt": {
                    "type": "string"
                },
                "duplicate": {
                    "type": "boolean"
                },
                "invocationID": {
                    "type": "string"
                },
                "metricsSubject": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "resultSubject": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "serverlessRequestID": {
                    "type": "string"
                },
                "stream": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "serverless.InvocationMode": {
            "type": "string",
            "enum": [
                "async",
                "sync"
            ],
            "x-enum-varnames": [
                "InvocationModeAsync",
                "InvocationModeSync"
            ]
        },
        "service.CreateGPUStorageRequest": {
            "type": "object",
            "properties": {
                "accessor": {
                    "$ref": "#/definitions/v1alpha1.GPUStorageAccessorSpec"
                },
                "name": {
                    "type": "string"
                },
                "prepare": {
                    "$ref": "#/definitions/v1alpha1.GPUStoragePrepareSpec"
                },
                "size": {
                    "type": "string"
                },
                "storageClassName": {
                    "type": "string"
                }
            }
        },
        "service.UpdateGPUStorageRequest": {
            "type": "object",
            "properties": {
                "accessor": {
                    "$ref": "#/definitions/v1alpha1.GPUStorageAccessorSpec"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "v1.Protocol": {
            "type": "string",
            "enum": [
                "TCP",
                "UDP",
                "SCTP"
            ],
            "x-enum-varnames": [
                "ProtocolTCP",
                "ProtocolUDP",
                "ProtocolSCTP"
            ]
        },
        "v1alpha1.GPUStorageAccessorSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "description": "Enabled turns on the built-in storage accessor deployment and service.",
                    "type": "boolean"
                }
            }
        },
        "v1alpha1.GPUStorageAccessorStatus": {
            "type": "object",
            "properties": {
                "accessURL": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUStoragePrepareSpec": {
            "type": "object",
            "properties": {
                "args": {
                    "description": "Args overrides the container args used by the data preparation job.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "description": "Command overrides the container command used by the data preparation job.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fromImage": {
                    "description": "FromImage is the image used by the data preparation job.",
                    "type": "string"
                },
                "fromStorageName": {
                    "description": "FromStorageName copies data from another storage object in the same namespace.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUStoragePrepareStatus": {
            "type": "object",
            "properties": {
                "jobName": {
                    "type": "string"
                },
                "observedDigest": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "recoveryPhase": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitAccess": {
            "type": "object",
            "properties": {
                "primaryPort": {
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitAllocationSpec": {
            "type": "object",
            "properties": {
                "capacity": {
                    "description": "Capacity contains DRA consumable capacity requests per device, for example memory or cores.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "claimName": {
                    "description": "ClaimName is the controller-owned DRA ResourceClaim name.",
                    "type": "string"
                },
                "claimRequestName": {
                    "description": "ClaimRequestName is the request name inside the DRA ResourceClaim.",
                    "type": "string"
                },
                "count": {
                    "description": "Count is the exact number of devices requested from the DeviceClass.\n+kubebuilder:validation:Minimum=0",
                    "type": "integer"
                },
                "deviceClassName": {
                    "description": "DeviceClassName is the DRA DeviceClass used for package-backed allocation.",
                    "type": "string"
                },
                "selectors": {
                    "description": "Selectors contains control-plane managed CEL selectors for DRA devices.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1alpha1.GPUUnitDRADeviceStatus": {
            "type": "object",
            "properties": {
                "consumedCapacity": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "device": {
                    "type": "string"
                },
                "driver": {
                    "type": "string"
                },
                "pool": {
                    "type": "string"
                },
                "request": {
                    "type": "string"
                },
                "shareID": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitDRAStatus": {
            "type": "object",
            "properties": {
                "allocated": {
                    "type": "boolean"
                },
                "claimName": {
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.GPUUnitDRADeviceStatus"
                    }
                }
            }
        },
        "v1alpha1.GPUUnitEnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitPortSpec": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "port": {
                    "description": "+kubebuilder:validation:Minimum=1\n+kubebuilder:validation:Maximum=65535",
                    "type": "integer"
                },
                "protocol": {
                    "$ref": "#/definitions/v1.Protocol"
                }
            }
        },
        "v1alpha1.GPUUnitSSHSpec": {
            "type": "object",
            "properties": {
                "authorizedKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "clientDomain": {
                    "type": "string"
                },
                "clientName": {
                    "type": "string"
                },
                "connectHost": {
                    "description": "ConnectHost is the user-facing HTTP CONNECT proxy host used in the ready-to-run SSH command.",
                    "type": "string"
                },
                "connectPort": {
                    "description": "+kubebuilder:validation:Minimum=1\n+kubebuilder:validation:Maximum=65535",
                    "type": "integer"
                },
                "domainSuffix": {
                    "description": "DomainSuffix is combined with name + namespace when ClientDomain is omitted.",
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "frpImage": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "port": {
                    "description": "+kubebuilder:validation:Minimum=1\n+kubebuilder:validation:Maximum=65535",
                    "type": "integer"
                },
                "serverAddr": {
                    "description": "ServerAddr is the FRP server address that the injected sidecar dials.",
                    "type": "string"
                },
                "serverPort": {
                    "description": "+kubebuilder:validation:Minimum=1\n+kubebuilder:validation:Maximum=65535",
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitSSHStatus": {
            "type": "object",
            "properties": {
                "accessCommand": {
                    "type": "string"
                },
                "connectHost": {
                    "type": "string"
                },
                "connectPort": {
                    "type": "integer"
                },
                "phase": {
                    "type": "string"
                },
                "targetHost": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitServerlessFrameworkSpec": {
            "type": "object",
            "properties": {
                "healthPath": {
                    "description": "HealthPath is the local HTTP path polled over the unix domain socket before dispatch consumption starts.",
                    "type": "string"
                },
                "invokePath": {
                    "description": "InvokePath is the local HTTP path received over the unix domain socket from the sidecar.",
                    "type": "string"
                },
                "socketPath": {
                    "description": "SocketPath is the shared unix domain socket path used by the sidecar and framework containers.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitServerlessSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "framework": {
                    "$ref": "#/definitions/v1alpha1.GPUUnitServerlessFrameworkSpec"
                },
                "idleTimeoutSeconds": {
                    "description": "+kubebuilder:validation:Minimum=0",
                    "type": "integer"
                },
                "minAvailableCount": {
                    "description": "+kubebuilder:validation:Minimum=0",
                    "type": "integer"
                },
                "minRequestCount": {
                    "description": "+kubebuilder:validation:Minimum=0",
                    "type": "integer"
                },
                "requestID": {
                    "description": "RequestID is the control-plane generated serverless request identifier shared by queued invocations and worker pools.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitServerlessStatus": {
            "type": "object",
            "properties": {
                "dispatchSubject": {
                    "type": "string"
                },
                "healthPath": {
                    "type": "string"
                },
                "invokePath": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "socketPath": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.GPUUnitStorageMount": {
            "type": "object",
            "properties": {
                "mountPath": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "readOnly": {
                    "type": "boolean"
                }
            }
        },
        "v1alpha1.GPUUnitTemplate": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "envs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.GPUUnitEnvVar"
                    }
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.GPUUnitPortSpec"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "GPU Operator Runtime API",
	Description:      "Control-plane API for the GPU operator runtime tutorial project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
