// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Return process and Kubernetes connectivity health for the runtime server.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operator/jobs/{operationID}": {
            "get": {
                "description": "Get the current state of an asynchronous stock pool creation operation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operator"
                ],
                "summary": "Get operation status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operation ID",
                        "name": "operationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OperatorJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operator/stockpools": {
            "get": {
                "description": "List StockPool custom resources and their observed runtime state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operator"
                ],
                "summary": "List stock pools",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace filter",
                        "name": "namespace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StockPoolListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Submit a StockPool creation request. Replays with the same operationID and payload are idempotent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operator"
                ],
                "summary": "Create a stock pool operation",
                "parameters": [
                    {
                        "description": "Create stock pool request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateStockPoolRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OperatorJobResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.OperatorJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.APIError"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.HealthStatus"
                }
            }
        },
        "api.OperatorJobResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.OperatorJob"
                }
            }
        },
        "api.StockPoolListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.StockPoolRuntime"
                    }
                }
            }
        },
        "domain.HealthStatus": {
            "type": "object",
            "properties": {
                "kubeError": {
                    "type": "string"
                },
                "kubernetesConnected": {
                    "type": "boolean"
                },
                "nodeCount": {
                    "type": "integer"
                },
                "startedAt": {
                    "type": "string"
                },
                "stockPoolCount": {
                    "type": "integer"
                },
                "uptimeSeconds": {
                    "type": "integer"
                }
            }
        },
        "domain.OperatorJob": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "objectName": {
                    "type": "string"
                },
                "objectNamespace": {
                    "type": "string"
                },
                "operationID": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.OperatorJobStatus"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.OperatorJobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "failed"
            ],
            "x-enum-varnames": [
                "OperatorJobPending",
                "OperatorJobRunning",
                "OperatorJobSucceeded",
                "OperatorJobFailed"
            ]
        },
        "domain.StockPoolRuntime": {
            "type": "object",
            "properties": {
                "allocatedReplicas": {
                    "type": "integer"
                },
                "availableReplicas": {
                    "type": "integer"
                },
                "desiredReplicas": {
                    "type": "integer"
                },
                "gpu": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "lastSyncTime": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "observedGeneration": {
                    "type": "integer"
                },
                "phase": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "specName": {
                    "type": "string"
                }
            }
        },
        "service.CreateStockPoolRequest": {
            "type": "object",
            "properties": {
                "gpu": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "operationID": {
                    "type": "string"
                },
                "replicas": {
                    "type": "integer"
                },
                "specName": {
                    "type": "string"
                },
                "template": {
                    "$ref": "#/definitions/v1alpha1.StockPoolTemplate"
                }
            }
        },
        "v1.Protocol": {
            "type": "string",
            "enum": [
                "TCP",
                "UDP",
                "SCTP"
            ],
            "x-enum-varnames": [
                "ProtocolTCP",
                "ProtocolUDP",
                "ProtocolSCTP"
            ]
        },
        "v1alpha1.StockPoolEnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.StockPoolPortSpec": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "port": {
                    "description": "+kubebuilder:validation:Minimum=1\n+kubebuilder:validation:Maximum=65535",
                    "type": "integer"
                },
                "protocol": {
                    "$ref": "#/definitions/v1.Protocol"
                }
            }
        },
        "v1alpha1.StockPoolTemplate": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "envs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.StockPoolEnvVar"
                    }
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.StockPoolPortSpec"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "GPU Operator Runtime API",
	Description:      "Control-plane API for the GPU operator runtime tutorial project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
