metricsBindAddress: ":8082"
healthProbeBindAddress: ":8081"
httpAddr: ":8080"
reportInterval: "30s"
leaderElect: false
metricsSecure: false
enableHTTP2: false
blockedEgressCIDRs:
  - "10.0.0.0/8"
  - "100.64.0.0/10"
  - "169.254.0.0/16"
  - "172.16.0.0/12"
  - "192.168.0.0/16"
