apiVersion: runtime.lokiwager.io/v1alpha1
kind: StockPool
metadata:
  labels:
    app.kubernetes.io/name: gpu-operator-runtime
    app.kubernetes.io/managed-by: kustomize
  name: stockpool-sample
spec:
  specName: g1.1
  image: python:3.12-slim
  memory: 8Gi
  gpu: 1
  replicas: 1
  template:
    command:
      - python
    args:
      - -m
      - http.server
      - "8080"
    envs:
      - name: MODEL_ID
        value: sample
    ports:
      - name: http
        port: 8080
        protocol: TCP
